services:
  oloy.earning_rule.param_converter:
    class: OpenLoyalty\Bundle\EarningRuleBundle\ParamConverter\EarningRuleParamConverter
    arguments: ['@oloy.earning_rule.repository']
    tags:
      - { name: request.param_converter, priority: 2, converter: earning_rule_converter }
  oloy.earning_rule.form_type.create:
    class: OpenLoyalty\Bundle\EarningRuleBundle\Form\Type\CreateEarningRuleFormType
    tags:
      - { name: form.type }
  oloy.earning_rule.form_type.edit:
    class: OpenLoyalty\Bundle\EarningRuleBundle\Form\Type\EditEarningRuleFormType
    tags:
      - { name: form.type }
  oloy.earning_rule.form_type.excluded_labels:
    class: OpenLoyalty\Bundle\EarningRuleBundle\Form\Type\ExcludedLabelsFormType
    tags:
      - { name: form.type }
  oloy.earning_rule.form_type.excluded_skus:
    class: OpenLoyalty\Bundle\EarningRuleBundle\Form\Type\ExcludedSKUsFormType
    tags:
      - { name: form.type }
  oloy.earning_rule.form_type.labels:
    class: OpenLoyalty\Bundle\EarningRuleBundle\Form\Type\LabelsFormType
    tags:
      - { name: form.type }
  oloy.earning_rule.listener:
    class: OpenLoyalty\Bundle\EarningRuleBundle\Event\Listener\EarningRuleSerializationListener
    arguments: ['@router']
    tags:
      - { name: jms_serializer.event_subscriber }
  oloy.earning_rule.algorithm_factory:
    class: OpenLoyalty\Bundle\EarningRuleBundle\Service\EarningRuleAlgorithmFactory
  oloy.earning_rule.validator:
    class: OpenLoyalty\Bundle\EarningRuleBundle\Service\OloyEarningRuleValidator
    arguments: ['@oloy.earning_rule.usage_repository', '@oloy.earning_rule.repository']

