imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl_PL
    storage_suffix: "_%kernel.environment%"
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    port:      '%mailer_port%'
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
        types:
          level_id: OpenLoyalty\Infrastructure\Level\Persistance\Doctrine\Type\LevelIdDoctrineType
          special_reward_id: OpenLoyalty\Infrastructure\Level\Persistance\Doctrine\Type\SpecialRewardIdDoctrineType
          earning_rule_id: OpenLoyalty\Infrastructure\EarningRule\Persistance\Doctrine\Type\EarningRuleIdDoctrineType
          earning_rule_usage_id: OpenLoyalty\Infrastructure\EarningRule\Persistance\Doctrine\Type\EarningRuleUsageIdDoctrineType
          earning_rule_usage_subject: OpenLoyalty\Infrastructure\EarningRule\Persistance\Doctrine\Type\EarningRuleUsageSubjectDoctrineType
          pos_id: OpenLoyalty\Infrastructure\Pos\Persistance\Doctrine\Type\PosIdDoctrineType
          labels_json_array: OpenLoyalty\Infrastructure\EarningRule\Persistance\Doctrine\Type\LabelsJsonArrayDoctrineType
          skus_json_array: OpenLoyalty\Infrastructure\EarningRule\Persistance\Doctrine\Type\SKUsJsonArrayDoctrineType
          sku: OpenLoyalty\Infrastructure\Model\Persistance\Doctrine\Type\SKUDoctrineType
          ol_geo_point: OpenLoyalty\Infrastructure\Pos\Persistance\Doctrine\Type\GeoPointDoctrineType
          segment_id: OpenLoyalty\Infrastructure\Segment\Persistance\Doctrine\Type\SegmentIdDoctrineType
          segment_part_id: OpenLoyalty\Infrastructure\Segment\Persistance\Doctrine\Type\SegmentPartIdDoctrineType
          criterion_id: OpenLoyalty\Infrastructure\Segment\Persistance\Doctrine\Type\CriterionIdDoctrineType
          campaign_id: OpenLoyalty\Infrastructure\Campaign\Persistance\Doctrine\Type\CampaignIdDoctrineType
          campaign_levels_json_array: OpenLoyalty\Infrastructure\Campaign\Persistance\Doctrine\Type\CampaignLevelsJsonArrayDoctrineType
          campaign_segments_json_array: OpenLoyalty\Infrastructure\Campaign\Persistance\Doctrine\Type\CampaignSegmentsJsonArrayDoctrineType
          campaign_coupons_json_array: OpenLoyalty\Infrastructure\Campaign\Persistance\Doctrine\Type\CampaignCouponsJsonArrayDoctrineType
          audit_log_id: OpenLoyalty\Infrastructure\Audit\Persistance\Doctrine\Type\AuditLogIdDoctrineType
          email_id: OpenLoyalty\Infrastructure\Email\Persistance\Doctrine\Type\EmailIdDoctrineType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
          OpenLoyaltyUserBundle: ~
          OpenLoyalty\Infrastructure\Level\Peristance\Doctrine\ORM:
            type: yml
            dir: '%kernel.root_dir%/../src/OpenLoyalty/Infrastructure/Level/Persistance/Doctrine/ORM'
            alias: OpenLoyaltyDomainLevel
            prefix: OpenLoyalty\Domain\Level
            is_bundle: false
          OpenLoyalty\Infrastructure\EarningRule\Peristance\Doctrine\ORM:
            type: yml
            dir: '%kernel.root_dir%/../src/OpenLoyalty/Infrastructure/EarningRule/Persistance/Doctrine/ORM'
            alias: OpenLoyaltyDomainEarningRule
            prefix: OpenLoyalty\Domain\EarningRule
            is_bundle: false
          OpenLoyalty\Infrastructure\Pos\Peristance\Doctrine\ORM:
            type: yml
            dir: '%kernel.root_dir%/../src/OpenLoyalty/Infrastructure/Pos/Persistance/Doctrine/ORM'
            alias: OpenLoyaltyDomainPos
            prefix: OpenLoyalty\Domain\Pos
            is_bundle: false
          OpenLoyalty\Infrastructure\Segment\Peristance\Doctrine\ORM:
            type: yml
            dir: '%kernel.root_dir%/../src/OpenLoyalty/Infrastructure/Segment/Persistance/Doctrine/ORM'
            alias: OpenLoyaltyDomainSegment
            prefix: OpenLoyalty\Domain\Segment
            is_bundle: false
          OpenLoyalty\Infrastructure\Campaign\Peristance\Doctrine\ORM:
            type: yml
            dir: '%kernel.root_dir%/../src/OpenLoyalty/Infrastructure/Campaign/Persistance/Doctrine/ORM'
            alias: OpenLoyaltyDomainCampaign
            prefix: OpenLoyalty\Domain\Campaign
            is_bundle: false
          OpenLoyalty\Infrastructure\Email\Peristance\Doctrine\ORM:
            type: yml
            dir: '%kernel.root_dir%/../src/OpenLoyalty/Infrastructure/Email/Persistance/Doctrine/ORM'
            alias: OpenLoyaltyDomainEmail
            prefix: OpenLoyalty\Domain\Email
            is_bundle: false
          OpenLoyalty\Infrastructure\Audit\Peristance\Doctrine\ORM:
            type: yml
            dir: '%kernel.root_dir%/../src/OpenLoyalty/Infrastructure/Audit/Persistance/Doctrine/ORM'
            alias: OpenLoyaltyDomainAudit
            prefix: OpenLoyalty\Domain\Audit
            is_bundle: false

broadway:
    read_model:
        repository: elasticsearch
        elasticsearch:
          hosts: "%elastica_host%:%elastica_port%"
    command_handling:
      dispatch_events: true

nelmio_api_doc:
    sandbox:
        request_format:
            method: accept_header

jms_serializer:
    visitors:
        json:
            options: JSON_PRETTY_PRINT
    metadata:
      auto_detection: true
      debug: true
      directories:
        Account:
          namespace_prefix: "OpenLoyalty\\Domain\\Account"
          path: "@OpenLoyaltyPointsBundle/Resources/config/serializer"
        Customer:
          namespace_prefix: "OpenLoyalty\\Domain\\Customer"
          path: "@OpenLoyaltyUserBundle/Resources/config/serializer"
        Seller:
          namespace_prefix: "OpenLoyalty\\Domain\\Seller"
          path: "@OpenLoyaltyUserBundle/Resources/config/serializer/Seller"
        Level:
          namespace_prefix: "OpenLoyalty\\Domain\\Level"
          path: "@OpenLoyaltyLevelBundle/Resources/config/serializer"
        EarningRule:
          namespace_prefix: "OpenLoyalty\\Domain\\EarningRule"
          path: "@OpenLoyaltyEarningRuleBundle/Resources/config/serializer"
        Pos:
          namespace_prefix: "OpenLoyalty\\Domain\\Pos"
          path: "@OpenLoyaltyPosBundle/Resources/config/serializer"
        Transaction:
          namespace_prefix: "OpenLoyalty\\Domain\\Transaction"
          path: "@OpenLoyaltyTransactionBundle/Resources/config/serializer"
        Segment:
          namespace_prefix: "OpenLoyalty\\Domain\\Segment"
          path: "@OpenLoyaltySegmentBundle/Resources/config/serializer"
        Campaign:
          namespace_prefix: "OpenLoyalty\\Domain\\Campaign"
          path: "@OpenLoyaltyCampaignBundle/Resources/config/serializer"
        Audit:
          namespace_prefix: "OpenLoyalty\\Domain\\Audit"
          path: "@OpenLoyaltyAuditBundle/Resources/config/serializer"
        Email:
          namespace_prefix: "OpenLoyalty\\Domain\\Email"
          path: "@OpenLoyaltyEmailSettingsBundle/Resources/config/serializer"
        Domain:
          namespace_prefix: "OpenLoyalty\\Domain\\"
          path: "%kernel.root_dir/serializer"
fos_rest:
    versioning: true
    routing_loader:
        include_format: true
        default_format: json
    param_fetcher_listener: force
    allowed_methods_listener: true
    disable_csrf_role: ROLE_USER
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }

    view:
        view_response_listener: 'force'
        formats:
            json: true
lexik_jwt_authentication:
    private_key_path: "%jwt_private_key_path%"
    public_key_path:  "%jwt_public_key_path%"
    pass_phrase:      "%jwt_key_pass_phrase%"
    token_ttl:        "%jwt_token_ttl%"
nelmio_cors:
    paths:
      '^/api/':
          allow_origin: ['*']
          allow_headers: ['*']
          allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
          max_age: 3600
gesdinet_jwt_refresh_token:
    ttl_update: true
    user_provider: oloy.user.all_users_provider

open_loyalty_user:
  customer_search_max_results: %customer_search_max_results%

open_loyalty_pagination:
    page_field_name: page
    per_page_field_name: perPage
    sort_field_name: sort
    sort_direction_field_name: direction
    per_page_default: 10

monolog:
    handlers:
        # this "file_log" key could be anything
        file_log:
            type: stream
            path: "%kernel.logs_dir%/plugin.log"
            # log *all* messages (debug is lowest level)
            level: debug
            channels: [plugins]

knp_gaufrette:
  adapters:
    frontend_translations:
      local:
        directory: "%kernel.root_dir%/Resources/frontend_translations"
        create:     true
    campaign_photos_local:
      local:
        directory: "%kernel.root_dir%/uploads/"
        create:     true
  filesystems:
    frontend_translations:
      adapter: frontend_translations
      alias: frontend_translations_filesystem
    campaign_photos:
      adapter: "%oloy.campaign.photos_adapter%"
      alias: campaign_photos_filesystem

open_loyalty_campaign:
  photos_adapter: "%campaign_photos_adapter%"
  photos_adapter_env: "%campaign_photos_adapter_env%"
  photos_min_width: 600
  photos_min_height: 600