open_loyalty_analytics:
    resource: "@OpenLoyaltyAnalyticsBundle/Resources/config/routing.yml"
    prefix:   /api

open_loyalty_campaign:
    resource: "@OpenLoyaltyCampaignBundle/Resources/config/routing.yml"
    prefix:   /api

open_loyalty_segment:
    resource: "@OpenLoyaltySegmentBundle/Resources/config/routing.yml"
    prefix:   /api

open_loyalty_pos:
    resource: "@OpenLoyaltyPosBundle/Resources/config/routing.yml"
    prefix:   /api

open_loyalty_earning_rule:
    resource: "@OpenLoyaltyEarningRuleBundle/Resources/config/routing.yml"
    prefix:   /api

open_loyalty_transaction:
    resource: "@OpenLoyaltyTransactionBundle/Resources/config/routing.yml"
    prefix:   /api

open_loyalty_settings:
    resource: "@OpenLoyaltySettingsBundle/Resources/config/routing.yml"
    prefix:   /api

open_loyalty_email_settings:
    resource: "@OpenLoyaltyEmailSettingsBundle/Resources/config/routing.yml"
    prefix:   /api

open_loyalty_points:
    resource: "@OpenLoyaltyPointsBundle/Resources/config/routing.yml"
    prefix:   /api

open_loyalty_level:
    resource: "@OpenLoyaltyLevelBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
api_admin_login_check:
    path: /api/admin/login_check
api_customer_login_check:
    path: /api/customer/login_check
api_seller_login_check:
    path: /api/seller/login_check
gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

oloy_user_api:
    resource: "@OpenLoyaltyUserBundle/Resources/config/api_routing.yml"
    prefix: /api
oloy_user:
    resource: "@OpenLoyaltyUserBundle/Resources/config/routing.yml"
    prefix: /
oloy_utility_api:
    resource: "@OpenLoyaltyUtilityBundle/Resources/config/routing.yml"
    prefix: /api
oloy_plugin_api:
    resource: "@OpenLoyaltyPluginBundle/Resources/config/routing.yml"
    prefix: /api
oloy_audit:
    resource: "@OpenLoyaltyAuditBundle/Resources/config/api_routing.yml"
    prefix:   /api