services:
  oloy.pagination:
    class: OpenLoyalty\Bundle\PaginationBundle\Service\Paginator
    arguments:
      - '%oloy.pagination.pageFieldName%'
      - '%oloy.pagination.perPageFieldName%'
      - '%oloy.pagination.sortFieldName%'
      - '%oloy.pagination.sortDirectionFieldName%'
      - '%oloy.pagination.perPageDefault%'
  oloy.pagination.checkbox_type_extension:
    class: OpenLoyalty\Bundle\PaginationBundle\Form\Extension\CheckboxTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CheckboxType }