OpenLoyalty\Domain\Segment\ReadModel\SegmentedCustomers:
  exlusion_policy: ALL
  properties:
    segmentId:
      expose: true
      inline: true
    customerId:
      expose: true
      inline: true
