services:
  oloy.user.customer.command_handler:
    class: OpenLoyalty\Domain\Customer\Command\CustomerCommandHandler
    arguments:
      - '@oloy.user.customer.repository'
      - '@oloy.user.customer.unique_validator'
      - '@broadway.event_dispatcher'
    lazy: true
    tags:
      - { name: command_handler }
  oloy.user.invitation.sha_token_generator:
    class: OpenLoyalty\Domain\Customer\Service\ShaInvitationTokenGenerator
    public: false

  oloy.user.invitation.token_generator: '@oloy.user.invitation.sha_token_generator'

  oloy.user.invitation.command_handler:
    class: OpenLoyalty\Domain\Customer\Command\InvitationCommandHandler
    arguments:
      - '@oloy.user.invitation.repository'
      - '@oloy.user.invitation.token_generator'
      - '@broadway.event_dispatcher'
    lazy: true
    tags:
      - { name: command_handler }
  oloy.user.seller.command_handler:
    class: OpenLoyalty\Domain\Seller\Command\SellerCommandHandler
    arguments:
      - '@oloy.user.seller.repository'
      - '@oloy.user.seller.unique_validator'
    lazy: true
    tags:
      - { name: command_handler }
  oloy.user.customer.unique_validator:
    class: OpenLoyalty\Domain\Customer\Validator\CustomerUniqueValidator
    arguments:
      - '@oloy.user.read_model.repository.customer_details'
  oloy.user.seller.unique_validator:
    class: OpenLoyalty\Domain\Seller\Validator\SellerUniqueValidator
    arguments:
      - '@oloy.user.read_model.repository.seller_details'
  oloy.user.customer.repository:
    class: OpenLoyalty\Domain\Customer\CustomerRepository
    arguments:
      - '@broadway.event_store'
      - '@broadway.event_handling.event_bus'
      - ['@broadway.metadata_enriching_event_stream_decorator']
  oloy.user.invitation.repository:
    class: OpenLoyalty\Domain\Customer\InvitationRepository
    arguments:
      - '@broadway.event_store'
      - '@broadway.event_handling.event_bus'
      - ['@broadway.metadata_enriching_event_stream_decorator']
  oloy.user.seller.repository:
    class: OpenLoyalty\Domain\Seller\SellerRepository
    arguments:
      - '@broadway.event_store'
      - '@broadway.event_handling.event_bus'
      - ['@broadway.metadata_enriching_event_stream_decorator']
  oloy.user.read_model.repository_factory:
    class: 'OpenLoyalty\Domain\Repository\OloyElasticsearchRepositoryFactory'
    arguments:
      - '@broadway.elasticsearch.client'
      - '@broadway.serializer.readmodel'
      - '%es_max_result_window_size%'
  oloy.user.read_model.repository.customer_details:
    class: 'Broadway\ReadModel\ReadModel'
    factory: ['@oloy.user.read_model.repository_factory', create]
    arguments:
      - 'oloy.customer_details'
      - 'OpenLoyalty\Domain\Customer\ReadModel\CustomerDetails'
      - 'OpenLoyalty\Domain\Repository\Customer\CustomerDetailsElasticsearchRepository'
  oloy.user.read_model.repository.invitation_details:
    class: 'Broadway\ReadModel\ReadModel'
    factory: ['@oloy.user.read_model.repository_factory', create]
    arguments:
      - 'oloy.invitation_details'
      - 'OpenLoyalty\Domain\Customer\ReadModel\InvitationDetails'
      - 'OpenLoyalty\Domain\Repository\Customer\InvitationDetailsElasticsearchRepository'
  oloy.user.read_model.repository.seller_details:
    class: 'Broadway\ReadModel\ReadModel'
    factory: ['@oloy.user.read_model.repository_factory', create]
    arguments:
      - 'oloy.seller_details'
      - 'OpenLoyalty\Domain\Seller\ReadModel\SellerDetails'
      - 'OpenLoyalty\Domain\Repository\Seller\SellerDetailsElasticsearchRepository'
  oloy.user.customer.read_model.projector.customer_details:
    class: 'OpenLoyalty\Domain\Customer\ReadModel\CustomerDetailsProjector'
    tags:
      - { name: broadway.domain.event_listener }
    arguments:
      - '@oloy.user.read_model.repository.customer_details'
      - '@oloy.transaction.read_model.repository.transaction_details'
  oloy.user.customer.read_model.projector.invitation_details:
    class: 'OpenLoyalty\Domain\Customer\ReadModel\InvitationDetailsProjector'
    tags:
      - { name: broadway.domain.event_listener }
    arguments:
      - '@oloy.user.read_model.repository.customer_details'
      - '@oloy.user.read_model.repository.invitation_details'
  oloy.user.customer.read_model.projector.seller_details:
    class: 'OpenLoyalty\Domain\Seller\ReadModel\SellerDetailsProjector'
    tags:
      - { name: broadway.domain.event_listener }
    arguments:
      - '@oloy.user.read_model.repository.seller_details'
      - '@oloy.pos.repository'

  oloy.user.read_model.repository.customers_belonging_to_one_level:
    class: 'Broadway\ReadModel\ReadModel'
    factory: ['@oloy.user.read_model.repository_factory', create]
    arguments:
      - 'oloy.customers_belonging_to_one_level'
      - 'OpenLoyalty\Domain\Customer\ReadModel\CustomersBelongingToOneLevel'
      - 'OpenLoyalty\Domain\Repository\Customer\CustomersBelongingToOneLevelElasticsearchRepository'
  oloy.user.customer.read_model.projector.customers_belonging_to_one_level:
    class: 'OpenLoyalty\Domain\Customer\ReadModel\CustomersBelongingToOneLevelProjector'
    tags:
      - { name: broadway.domain.event_listener }
    arguments:
      - '@oloy.user.read_model.repository.customer_details'
      - '@oloy.user.read_model.repository.customers_belonging_to_one_level'
      - '@oloy.level.repository'

  oloy.user.customer.listener.calculate_customer_level:
    class: 'OpenLoyalty\Infrastructure\Customer\SystemEvent\Listener\CalculateCustomerLevelListener'
    lazy: true
    tags:
      - { name: broadway.event_listener, event: oloy.transaction.customer_assigned, method: handle }
      - { name: broadway.event_listener, event: oloy.account.created, method: handle }
      - { name: broadway.event_listener, event: oloy.account.available_points_amount_changed, method: handle }
    arguments:
      - '@oloy.user.level_id_provider'
      - '@oloy.user.read_model.repository.customer_details'
      - '@broadway.command_handling.command_bus'
      - '@oloy.user.tier_assign_type_provider'
      - '@oloy.user.exclude_delivery_costs_provider'
      - '@oloy.level.repository'
      - '@broadway.event_dispatcher'
  oloy.user.customer.listener.create_account:
    class: 'OpenLoyalty\Infrastructure\Customer\SystemEvent\Listener\CreateAccountListener'
    tags:
      - { name: broadway.event_listener, event: oloy.customer.registered, method: handleCustomerRegistered }
    arguments:
      - '@broadway.command_handling.command_bus'
      - '@broadway.uuid.generator'

  oloy.user.seller.listener.pos_updated:
    class: 'OpenLoyalty\Infrastructure\Seller\SystemEvent\Listener\UpdatePosDataListener'
    tags:
      - { name: broadway.event_listener, event: oloy.pos.updated, method: handlePosUpdated }
    arguments:
      - '@oloy.user.read_model.repository.seller_details'
