parameters:
  oloy.emails:
      - { template: 'OpenLoyaltyUserBundle:email:registration.html.twig', subject: 'Account created', variables: ['url'] }
      - { template: 'OpenLoyaltyUserBundle:email:registration_with_temporary_password.html.twig', subject: 'Account created', variables: ['program_name', 'email', 'loyalty_card_number', 'phone', 'password', 'customer_panel_url'] }
      - { template: 'OpenLoyaltyUserBundle:email:password_reset.html.twig', subject: 'Password reset requested', variables: ['program_name', 'url_reset_password'] }
      - { template: 'OpenLoyaltyUserBundle:email:customer_reward_bought.html.twig', subject: '%s - new reward', variables: ['program_name', 'reward_name', 'reward_code', 'reward_instructions', 'ecommerce_address'] }
      - { template: 'OpenLoyaltyUserBundle:email:new_points.html.twig', subject: '%s - new points', variables: ['program_name', 'added_points_amount', 'active_points_amount', 'ecommerce_address'] }
      - { template: 'OpenLoyaltyUserBundle:email:new_level.html.twig', subject: '%s - new level', variables: ['program_name', 'level_name', 'level_discount', 'ecommerce_address'] }

services:
  oloy.user.all_users_provider:
    class: OpenLoyalty\Bundle\UserBundle\Service\UserProvider
    arguments:
      - '@doctrine.orm.entity_manager'
  oloy.user.admin_provider:
    class: OpenLoyalty\Bundle\UserBundle\Service\AdminProvider
    arguments:
      - '@doctrine.orm.entity_manager'
  oloy.user.seller_provider:
    class: OpenLoyalty\Bundle\UserBundle\Service\SellerProvider
    arguments:
      - '@doctrine.orm.entity_manager'
  oloy.user.customer_provider:
    class: OpenLoyalty\Bundle\UserBundle\Service\CustomerProvider
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@oloy.user.read_model.repository.customer_details'
  oloy.user.user_manager:
    class: OpenLoyalty\Bundle\UserBundle\Service\UserManager
    arguments:
      - '@security.password_encoder'
      - '@doctrine.orm.entity_manager'
      - '@oloy.user.password_generator'
      - '@oloy.user.email_provider'
      - '@oloy.user.read_model.repository.customer_details'
  oloy.user.event.authentication_success_listener:
    class: OpenLoyalty\Bundle\UserBundle\EventListener\AuthenticationListener
    arguments: ['@oloy.user.user_manager', '@broadway.event_dispatcher']
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }
  oloy.user.form_type.change_password:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\ChangePasswordFormType
    tags:
      - { name: form.type }
  oloy.user.form_type.admin:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\AdminFormType
    tags:
      - { name: form.type }
  oloy.user.form_type.password_reset:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\PasswordResetFormType
    tags:
      - { name: form.type }
  oloy.user.form_type.customer_registration:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\CustomerRegistrationFormType
    arguments: ['@oloy.level.repository', '@oloy.pos.repository']
    tags:
      - { name: form.type }
  oloy.user.form_type.customer_self_registration:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\CustomerSelfRegistrationFormType
    tags:
      - { name: form.type }
  oloy.user.form_type.customer_edit:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\CustomerEditFormType
    tags:
      - { name: form.type }

  oloy.user.form_type.seller_registration:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\SellerRegistrationFormType
    arguments:
      - '@oloy.pos.repository'
    tags:
      - { name: form.type }
  oloy.user.form_handler.customer_registration:
    class: OpenLoyalty\Bundle\UserBundle\Form\Handler\CustomerRegistrationFormHandler
    arguments:
      - '@broadway.command_handling.command_bus'
      - '@oloy.user.user_manager'
      - '@doctrine.orm.entity_manager'
      - '@broadway.uuid.generator'
      - '@oloy.user.customer.unique_validator'
  oloy.user.form_handler.seller_registration:
    class: OpenLoyalty\Bundle\UserBundle\Form\Handler\SellerRegistrationFormHandler
    arguments:
      - '@broadway.command_handling.command_bus'
      - '@oloy.user.user_manager'
      - '@doctrine.orm.entity_manager'
  oloy.user.form_handler.customer_edit:
    class: OpenLoyalty\Bundle\UserBundle\Form\Handler\CustomerEditFormHandler
    arguments:
      - '@broadway.command_handling.command_bus'
      - '@oloy.user.user_manager'
      - '@doctrine.orm.entity_manager'
      - '@oloy.user.customer.unique_validator'
  oloy.user.form_handler.seller_edit:
    class: OpenLoyalty\Bundle\UserBundle\Form\Handler\SellerEditFormHandler
    arguments:
      - '@broadway.command_handling.command_bus'
      - '@oloy.user.user_manager'
      - '@doctrine.orm.entity_manager'
  oloy.user.random_password_generator:
    class: OpenLoyalty\Bundle\UserBundle\Service\RandomStringPasswordGenerator
  oloy.user.password_generator:
    alias: 'oloy.user.random_password_generator'
  oloy.user.email_provider:
    class: OpenLoyalty\Bundle\UserBundle\Service\EmailProvider
    arguments:
      - '@oloy.email.message_factory'
      - '@oloy.mailer'
      - {from_name: '%mailer_from_name%', from_address: '%mailer_from_address%', password_reset_url: '%frontend_password_reset_url%', loyalty_program_name: '%loyalty_program_name%', ecommerce_address: '%ecommerce_address%', customer_panel_url: '%frontend_customer_panel_url%'}

  oloy.user.es_param_manager:
    class: OpenLoyalty\Bundle\UserBundle\Service\EsParamManager
  oloy.user.param_manager:
    alias: 'oloy.user.es_param_manager'

  oloy.user.listener.customer_serialization_listener:
    class: OpenLoyalty\Bundle\UserBundle\EventListener\CustomerSerializationListener
    arguments: ['@oloy.level.repository', '@ol.settings.manager', '@oloy.pos.repository']
    tags:
      - { name: jms_serializer.event_subscriber }

  oloy.user.level_id_provider:
    class: 'OpenLoyalty\Bundle\UserBundle\Service\OloyLevelIdProvider'
    arguments:
      - '@oloy.level.repository'


  oloy.user.settings_based_tier_assign_type_provider:
    class: 'OpenLoyalty\Bundle\UserBundle\Service\SettingsBasedTierAssignTypeProvider'
    arguments:
      - '@ol.settings.manager'

  oloy.user.settings_based_exclude_delivery_costs_provider:
    class: 'OpenLoyalty\Bundle\UserBundle\Service\SettingsBasedExcludeDeliveryCostsProvider'
    arguments:
      - '@ol.settings.manager'

  oloy.user.tier_assign_type_provider:
    alias: oloy.user.settings_based_tier_assign_type_provider
  oloy.user.exclude_delivery_costs_provider:
    alias: oloy.user.settings_based_exclude_delivery_costs_provider

  oloy.user.random_number_token_generator:
    class: OpenLoyalty\Bundle\UserBundle\Service\RandomNumberTokenGenerator

  oloy.user.token_generator:
    alias: oloy.user.random_number_token_generator

  oloy.customer_status_provider:
    class: OpenLoyalty\Bundle\UserBundle\Status\CustomerStatusProvider
    arguments:
      - '@oloy.points.account.repository.account_details'
      - '@oloy.level.repository'
      - '@oloy.user.read_model.repository.customer_details'
      - '@oloy.user.tier_assign_type_provider'
      - '@oloy.user.exclude_delivery_costs_provider'
      - '@ol.settings.manager'
  oloy.user.param_converter.customer:
    class: OpenLoyalty\Bundle\UserBundle\ParamConverter\CustomerDetailsParamConverter
    arguments: ['@oloy.user.read_model.repository.customer_details']
    tags:
      - { name: request.param_converter, priority: -2, converter: customer_details_converter }
  oloy.user.param_converter.seller:
    class: OpenLoyalty\Bundle\UserBundle\ParamConverter\SellerDetailsParamConverter
    arguments: ['@oloy.user.read_model.repository.seller_details']
    tags:
      - { name: request.param_converter, priority: -2, converter: seller_details_converter }
  oloy.user.guard.token:
    class: OpenLoyalty\Bundle\UserBundle\Security\Authenticator\TokenAuthenticator
    public: false

  oloy.user.doctrine_repository.admin:
    class: OpenLoyalty\Bundle\UserBundle\Entity\Repository\DoctrineAdminRepository
    factory:
      - '@doctrine.orm.default_entity_manager'
      - getRepository
    arguments:
      - 'OpenLoyalty\Bundle\UserBundle\Entity\Admin'

  oloy.user.repository.admin:
    alias: oloy.user.doctrine_repository.admin

  oloy.user.admin.command_handler:
      class: OpenLoyalty\Bundle\UserBundle\CQRS\Handler\AdminHandler
      arguments:
        - '@oloy.user.user_manager'
        - '@broadway.uuid.generator'
        - '@oloy.user.repository.admin'
      lazy: true
      tags:
        - { name: command_handler }

  oloy.user.listener.customer_level_changed:
      class: OpenLoyalty\Bundle\UserBundle\EventListener\CustomerLevelChangedListener
      arguments:
        - '@oloy.user.email_provider'
        - '@oloy.level.repository'
        - '@oloy.user.read_model.repository.customer_details'
      tags:
        - { name: broadway.event_listener, event: oloy.customer.level_changed, method: sendEmail }
